### ISSUE TITLE
Icons won't load

### ISSUE THREAD

**Issue by zhouska** [drawbars37/BAWicons#3]
For some reason, the icons won't load at all:

my configuration.yaml:
```
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /local/hass-baw-icons.js
    - /local/community/custom-brand-icons/custom-brand-icons.js
```
and output from hacs:

```
[core-ssh ~]$ ls -la config/www/
total 136
drwxr-xr-x    3 root     root          4096 Jun  6 08:45 .
drwxr-xr-x   11 root     root          4096 Jun  6 10:47 ..
drwxr-xr-x    6 root     root          4096 Jun  6 09:35 community
-rw-r--r--    1 root     root        125708 Jun  6 08:44 hass-baw-icons.js
[core-ssh ~]$ ls -la config/www/community/custom-brand-icons/
total 6616
drwxr-xr-x    2 root     root          4096 Jun  6 09:35 .
drwxr-xr-x    6 root     root          4096 Jun  6 09:35 ..
-rw-r--r--    1 root     root       4983648 Jun  6 09:35 custom-brand-icons.js
-rw-r--r--    1 root     root       1778561 Jun  6 09:35 custom-brand-icons.js.gz
[core-ssh ~]$
```
Only BAW icons will not load. Tried also moving the js file to community folder, to no avail:

```
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /local/community/hass-baw-icons.js
    - /local/community/custom-brand-icons/custom-brand-icons.js
```

HACS was restarted, to no avail. The other icons load without any issues.
